name: Master
on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/5 */2 * */2 1-5'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Running
      run:
        echo "Running"
